"""Add bot_texts table

Revision ID: 1b69bdc66d53
Revises: c843c9d6f609
Create Date: 2026-07-27 11:29:45.008390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b69bdc66d53'
down_revision: Union[str, Sequence[str], None] = 'c843c9d6f609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'language', name='uq_bot_texts_key_lang')
    )
    op.create_index(op.f('ix_bot_texts_key'), 'bot_texts', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_texts_key'), table_name='bot_texts')
    op.drop_table('bot_texts')
    # ### end Alembic commands ###
