"""Add tiktok_username column to users

Revision ID: 86effd369dec
Revises: 1b69bdc66d53
Create Date: 2026-07-27 15:51:40.254388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86effd369dec'
down_revision: Union[str, Sequence[str], None] = '1b69bdc66d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tiktok_username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tiktok_username')
    # ### end Alembic commands ###
