"""Compatibility facade for the TikTok Telegram presentation adapter.

New code should import from :mod:`presentation.telegram.tiktok.handlers`.
"""

from presentation.telegram.tiktok.handlers import (
    AnimatedStatus,
    _comments_cache,
    _post_urls_cache,
    auto_download_tiktok_link,
    back_to_photo_mode,
    close_tiktok_comments,
    cmd_mtiktok,
    cmd_ptiktok,
    download_all_slides,
    download_selected_slides,
    enter_slides_selection_mode,
    format_user_caption,
    navigate_tiktok_comment_card,
    process_audio_link_input,
    process_photo_link_input,
    process_username_input,
    register_post_url,
    render_comment_card,
    router,
    show_tiktok_account_menu,
    start_bind_username,
    start_tiktok_comments_card,
    tiktok_cancel,
    tiktok_service,
    tiktok_unbind_confirm,
    tiktok_unbind_yes,
    toggle_slide_selection,
    translate_tiktok_comment_card,
)

__all__ = [
    "AnimatedStatus",
    "_comments_cache",
    "_post_urls_cache",
    "auto_download_tiktok_link",
    "back_to_photo_mode",
    "close_tiktok_comments",
    "cmd_mtiktok",
    "cmd_ptiktok",
    "download_all_slides",
    "download_selected_slides",
    "enter_slides_selection_mode",
    "format_user_caption",
    "navigate_tiktok_comment_card",
    "process_audio_link_input",
    "process_photo_link_input",
    "process_username_input",
    "register_post_url",
    "render_comment_card",
    "router",
    "show_tiktok_account_menu",
    "start_bind_username",
    "start_tiktok_comments_card",
    "tiktok_cancel",
    "tiktok_service",
    "tiktok_unbind_confirm",
    "tiktok_unbind_yes",
    "toggle_slide_selection",
    "translate_tiktok_comment_card",
]
